### PR TITLE
extent example to show information from the users profile

### PR DESCRIPTION
**Pull request by CarstenKoenig**
- expose raw claims text
-  to turn this into a user provided  instance
- extented the example to show Email-Address and Picture from claims (works with Google)

### CODE REVIEW

**Comment by CarstenKoenig** [comment]
Hi,

I noticed that it's kind of hard to access additional claims that might be included in the JWT.

The example itself includes the user profile and email, so things like `email`, `name`, `picture` are there but hard to access.

Based on how the `IdTokenClaims` itself are handled I thought it'd nice if a user of your library could access the *raw* `ByteString` if the user wants to - or alternatively use `decodePublicClaims` and a self-defined `Data.Aeson.FromJSON` instance to get the interesting data out.
If you like that I could probably continue and expose common types like `profile` as build-in additional/`Maybe` fields into the `IdTokenClaims`

Please let me know what you think.

Thank you!

**Comment by krdlab** [comment]
@CarstenKoenig 
Thank you for your good PR. I'll review it at end of this weekend.
Sorry for being late reply.

**Comment by CarstenKoenig** [comment]
> @CarstenKoenig
> Thank you for your good PR. I'll review it at end of this weekend.
> Sorry for being late reply.

thanks - seems most of what I tried to achieve here is already merged (a bit different)

the only salvageable parts seems to be the display of name and photo in the example

I guess giving back the raw JwtToken / Value is probably obsolete with this

---

do you want me to update the PR like this?

**Comment by CarstenKoenig** [comment]
I've updated the example (shows name, email and the profile-picture)

there is really nothing more to it - you did all the work. Maybe you'll find this still useful.

Thanks for this (needed a way to access profile information easily)

**Review by krdlab — APPROVED** [review]
Great! Your update is perfect.
In addition, I'm glad your proposal for improvement. Thanks.

**Pull request merged**
