### PR TITLE
Fix unsupported algorithm error

### LINKED ISSUE #35: Ignore unsupported algorithms
I am using [Keycloak](https://www.keycloak.org/) as my OIDC provider, and the well-known endpoint advertises `PS384` as a supported signing algorithm. Parsing the JSON [fails in this case](https://github.com/krdlab/haskell-oidc-client/blob/0b88924036fe1e79ed00e5cbcd30016be39f07c4/src/Web/OIDC/Client/Discovery/Provider.hs#L44), however this is not ideal. Would it be possible to ignore unsupported algorithms?

### PR DESCRIPTION
**Pull request by krdlab**
Fix #35

### CODE REVIEW

**Comment by rdelgatte** [comment]
Hello @krdlab, glad to see this feature being in progress. 
I am looking forward to see it ready so if you need any feedback / early tester / help, I'll be happy to help you!

**Comment by krdlab** [comment]
I tested the PR using keycloak and another IdP. It worked fine.

**Comment by rdelgatte** [comment]
Thank you @krdlab for this feature. I tested it and it works fine! 

BTW, I noticed an issue when appending the `"/.well-known/openid-configuration"` to the request location (with the IDP I use right now) as I get this as `req'` after appending the path suffix: 
```
Request {
  host                 = "my-idp-host.com"
  port                 = 443
  secure               = True
  requestHeaders       = []
  path                 = "//.well-known/openid-configuration"
  queryString          = ""
  method               = "GET"
  proxy                = Nothing
  rawBody              = False
  redirectCount        = 10
  responseTimeout      = ResponseTimeoutDefault
  requestVersion       = HTTP/1.1
}
```
This fails when discovering the configuration as `https://my-idp-host.com//.well-known/openid-configuration` returns a 404. 

- Did you experience the same? 
- Shouldn't we change the suffix to `".well-known/openid-configuration"` to prevent this?

Thank you again for this change!

**Comment by krdlab** [comment]
@rdelgatte 
Thank you for your feedback.

Does the Issuer location which is the argument of 'discover' function have a trailing slash?
I suppose that removing the ending slash would resolve your problem.

**Comment by rdelgatte** [comment]
I thought about that but it did not contain any trailing slash so I tried to `print` the result `req'` and got what I highlighted before (where the host ends with `.com` and the `path` is `"//.well-known/openid-configuration"`).

It is part of another issue so I guess you can merge this PR and I'll investigate in another issue to track this down.

**Review by rdelgatte — APPROVED** [review]

**Comment by krdlab** [comment]
@rdelgatte 
Thank you again for your feedbacks!

**Pull request merged**
