### PR TITLE
Add implicit id_token flow

### PR DESCRIPTION
**Pull request by eborden**
There are a few unrelated prefactor changes here, namely adding tooling configuration files.

### Add implicit id_token flow

Some auth servers only allow the implicit flow for fetching an
`id_token`. This flow is very straight forward, but it requires a few
different steps than auth code.

1. The client requests a `response_type` `id_token`.
2. The request must contain `response_mode=form_post` otherwise the
   identity server will return parameters in the hash fragment.
3. The `id_token` can then be validated by the client.

### `MonadCatch` and `MonadThrow`

This pull request does not utilize `MonadCatch` or `MonadThrow`. My specific use case is utilizing `yesod-auth`, which requires authorization dispatch to exist within an abstract handler.

```
type MonadAuthHandler master m = (MonadHandler m, YesodAuth master, master ~ HandlerSite m, Auth ~ SubHandlerSite m, MonadUnliftIO m)
```

That handler does not include `MonadCatch` or `MonadThrow`. So the use of those constraints was prohibitive. Since all of the throwing and catching in this library happens within `IO`, it is not necessary to use `MonadCatch` and `MonadThrow`. I have excluded them from this PR.

### CODE REVIEW

**Comment by eborden** [comment]
Note, one incompatibility with the implicit flow and this library is the requirement of a `client_secret` to build an `OIDC`.

**Comment by krdlab** [comment]
Thank you for your PR. I'll review the PR at this weekend.

**Comment by eborden** [comment]
@krdlab have you had a chance to look at this?

**Review by krdlab — APPROVED** [review]
I'm really sorry for being late.
I reviewed the PR. It Looks good to me. Thanks again.

**Pull request merged**
