### PR TITLE
Security improvements: validating nonce and specifying signing algorithms

### PR DESCRIPTION
**Pull request by igrep**
I'll open this Pull request after merging https://github.com/krdlab/haskell-oidc-client/pull/23 (because this PR depends on that) and test the flow by myself.
See the commit messages for details.

### CODE REVIEW

**Comment by igrep** [comment]
Tested the normal case manually.

**Comment by igrep** [comment]
Oh, my... the commit in https://github.com/krdlab/haskell-oidc-client/pull/23 has been contained by this pull request.
Sorry, ignore it.

**Comment by igrep** [comment]
@krdlab Ping. Are you busy now?

**Comment by krdlab** [comment]
@igrep Sorry. I'll review the PR after work tonight.

**Review by krdlab — APPROVED** [review]
Thank you for your PR. It looks great to me! 🥇 
I tested, it worked fine.
Thanks again.

**Pull request merged**
